# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  apt_packages:
    - ruby-full
    - build-essential
    - zlib1g-dev
  commands:
    - GEM_HOME="$HOME/gems" PATH="$HOME/gems/bin:$PATH" gem install jekyll bundler
    - cd docs && $HOME/gems/bin/bundle install
    - cd docs && $HOME/gems/bin/bundle exec jekyll build --destination ../_readthedocs/html
