# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - ruby-full
    - build-essential
    - zlib1g-dev
    - rbenv
  jobs:
   pre_install:
      - rbenv local
      - rbenv global
      - rbenv exec gem install bundler
      - cd docs && rbenv exec bundle install
      - cd docs && rbenv exec bundle exec jekyll build --destination ../_readthedocs/html
