# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  commands:
    - curl -sSL https://get.rvm.io | bash -s stable
    - source ~/.rvm/scripts/rvm && rvm install ruby 3.1.2
    - source ~/.rvm/scripts/rvm && cd docs && gem install bundler
    - source ~/.rvm/scripts/rvm && cd docs && bundle install
    - source ~/.rvm/scripts/rvm && cd docs && bundle exec jekyll build --destination ../_readthedocs/html
