name: Cookie test
description: Use cookie cutter to build and install
inputs:
  backend:
    description: Which backend to use
    required: true

runs:
  using: composite
  steps:
    - name: "${{ inputs.backend }}: Run cookiecutter"
      shell: bash
      run: |
        cookiecutter --no-input . --config-file tests/${{ inputs.backend }}.yml
        git add .

    - name: "${{ inputs.backend }}: Install package"
      shell: bash
      run: python -m pip install ./cookie-${{ inputs.backend }}[test]

    - name: "${{ inputs.backend }}: Test package"
      shell: bash
      run: (cd cookie-${{ inputs.backend }} && python -m pytest -ra)

    - name: "${{ inputs.backend }}: Uninstall"
      shell: bash
      run: |
        pip uninstall -y cookie_${{ inputs.backend }}
        rm -r ./cookie-${{ inputs.backend }}
        git reset
