name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - main
    - develop

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Prepare pre-commit
      run: |
        pip install wheel
        pip install cookiecutter pre-commit

    - uses: ./.github/actions/cookie_precommit
      with:
        backend: setuptools

    - uses: ./.github/actions/cookie_precommit
      with:
        backend: pybind11



  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.9]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

        include:
        - python-version: pypy-3.6
          runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install cookiecutter
      run: |
        pip install wheel
        pip install cookiecutter

    - uses: ./.github/actions/cookie_test
      with:
        backend: setuptools
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: 0.1.0

    - uses: ./.github/actions/cookie_test
      with:
        backend: pybind11
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: 0.1.0


  dist:
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Install wheel and sdist requirements
      run: python -m pip install build cookiecutter

    - name: Run cookiecutter
      run: |
        cookiecutter --no-input . --config-file tests/setuptools.yml
        cookiecutter --no-input . --config-file tests/pybind11.yml

    - name: Build sdist and wheel
      run: |
        python -m build cookie-setuptools -o dist
        python -m build cookie-pybind11 -o dist
        ls -l dist
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: 0.1.0

    - uses: actions/upload-artifact@v2
      with:
        path: dist
